### ISSUE TITLE
Grouping files (audio, docs, images) in 'Oral History' Omeka Items

### ISSUE THREAD

**Issue by sharynys** [ozmeka/ozmeka#1]
Use case: User is interested in the rare Linseed Cormorant and it happens to be in one of the photos (bird.jpg) that accompanies this Oral History, although it is not mentioned in the transcript document. 'Linseed Cormorant' can be added to the Species field of the Oral History item, but there is no way to indicate that this subject relates to bird.jpg. 

Although metadata can be added for the file (by editing the file within the item), this metadata is not visible to the user. Currently file (i.e. non exif) metadata can only be returned via a search in the admin interface.

**Comment by ptsefton** [comment]
Potentially this kind of thing could be solved by the solr index model, it is possible to index hierarchical relationships (at least sort-of). Or at least index files that have their own metadata separately as well as the main items, and allow discovery that way.

**Comment by sharynys** [comment]
I have got solr working. The solr plugin implementation is a bit underwhelming - no full text search that I can get working yet (trying to use it with the Pdftext plugin) and no faceted browsing - facets are only used for filtering.  Need faceted browsing to enable a landing page for subcollections. I will add these to the specs list.  I think I may have been spoiled by Greenstone DL and its direct access to Lucene indexes and config.

**Comment by sharynys** [comment]
before you accuse me of being negative :-), this doesn't mean I don't like Omeka. I hope we can extend the Solr plugin to achieve these things - which I do think these are fairly fundamental reqs for a DORA these days.
