### ISSUE TITLE
Investigate why DC harvesting from GeoNode to Omeka Does Not Work

### ISSUE THREAD

**Issue by kevinpdavies** [ozmeka/ozmeka#16]
Harvesting from Omeka to GeoNetwork (DC) works OK. However, it does not work with GeoNode. The URL for harvesting from GeoNode works OK in the browser:

```
http://144.6.225.213/catalogue/csw?mode=oaipmh&verb=ListRecords&set=citable&metadataPrefix=oai_dc
```

**Comment by kevinpdavies** [comment]
A "ListRecords" response against a GeoNetwork (which works with Omeka):

```
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI- PMH.xsd">
<responseDate>2015-04-09T10:56:13Z</responseDate>
<request verb="ListRecords"  metadataPrefix="oai_dc">http://144.6.225.213:80/geonetwork/srv/en/oaipmh</request>
<ListRecords>
<record>
<header>
    <identifier>2714a7f3-338a-4d14-b8e6-23a504108442</identifier>
    <datestamp>2015-03-26T14:26:59Z</datestamp>
 </header>
       .......
```

The same from GeoNode (which doesn't work) - elements are prefixed by "oai:"

```
<oai:OAI-PMH xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<oai:responseDate>2015-04-08T20:15:24Z</oai:responseDate>
<oai:request metadataprefix="oai_dc" verb="ListRecords">http://144.6.225.213/catalogue/csw?mode=oaipmh</oai:request>
<oai:ListRecords>
<oai:record>
<oai:header>  
    <oai:identifier>3eecd6aa-d745-11e4-b68d-fa163eac73e2</oai:identifier>
    <oai:dateStamp/>
    <oai:setSpec/>
</oai:header>
       .......
```

Need to see if this is correct XML for harvesting (I haven't found an example of the use of the oai: namespace), and whether this is actually causing the Omeka Plugin to ignore the response

**Comment by ptsefton** [comment]
If you look at the namespaces they are different.

The one that works has an implicit namespace of :
http://www.openarchives.org/OAI/2.0/

The one that doesn't work has an explicit namespace of
http://www.openarchives.org/OAI/2.0/oai_dc/ - which appears to be correct
as per the spec: http://www.openarchives.org/OAI/openarchivesprotocol.html

If it is using an XML parser then this could be the problem - not the use
of the prefix but the URI for the namespace is unexpected the plugin is
hard coded to use the shorter version:
https://github.com/omeka/plugin-OaipmhHarvester/blob/master/models/OaipmhHarvester/Harvest/OaiDc.php

On Thu, Apr 9, 2015 at 11:18 AM, Kevin Davies notifications@github.com
wrote:

> A "ListRecords" response against a GeoNetwork (which works with Omeka):
> 
> <OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI- PMH.xsd">
> <responseDate>2015-04-09T10:56:13Z</responseDate>
> <request verb="ListRecords"  metadataPrefix="oai_dc">http://144.6.225.213:80/geonetwork/srv/en/oaipmh</request>
> <ListRecords>
> <record>
> <header>
>     <identifier>2714a7f3-338a-4d14-b8e6-23a504108442</identifier>
>     <datestamp>2015-03-26T14:26:59Z</datestamp>
>  </header>
>        .......
> 
> The same from GeoNode (which doesn't work) - elements are prefixed by
> "oai:"
> 
> <oai:OAI-PMH xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
> oai:responseDate2015-04-08T20:15:24Z/oai:responseDate
> <oai:request metadataprefix="oai_dc" verb="ListRecords">http://144.6.225.213/catalogue/csw?mode=oaipmh/oai:request
> oai:ListRecords
> oai:record
> oai:header
>     oai:identifier3eecd6aa-d745-11e4-b68d-fa163eac73e2/oai:identifier
>     oai:dateStamp/
>     oai:setSpec/
> /oai:header
>        .......
> 
> Need to see if this is correct XML for harvesting (I haven't found an
> example of the use of the oai: namespace), and whether this is actually
> causing the Omeka Plugin to ignore the response
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ozmeka/ozmeka/issues/16#issuecomment-91084180.

## 

Peter Sefton +61410326955 pt@ptsefton.com http://ptsefton.com
Gmail, Twitter & Skype name: ptsefton

**Comment by ptsefton** [comment]
Actually - I got that wrong about the namespace it has the correct one from
the spec  as a constant.

https://github.com/omeka/plugin-OaipmhHarvester/blob/master/models/OaipmhHarvester/Harvest/OaiDc.php#L22

On Thu, Apr 9, 2015 at 11:37 AM, Peter (pt) Sefton pt@ptsefton.com wrote:

> If you look at the namespaces they are different.
> 
> The one that works has an implicit namespace of :
> http://www.openarchives.org/OAI/2.0/
> 
> The one that doesn't work has an explicit namespace of
> http://www.openarchives.org/OAI/2.0/oai_dc/ - which appears to be correct
> as per the spec: http://www.openarchives.org/OAI/openarchivesprotocol.html
> 
> If it is using an XML parser then this could be the problem - not the use
> of the prefix but the URI for the namespace is unexpected the plugin is
> hard coded to use the shorter version:
> https://github.com/omeka/plugin-OaipmhHarvester/blob/master/models/OaipmhHarvester/Harvest/OaiDc.php
> 
> On Thu, Apr 9, 2015 at 11:18 AM, Kevin Davies notifications@github.com
> wrote:
> 
> > A "ListRecords" response against a GeoNetwork (which works with Omeka):
> > 
> > <OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI- PMH.xsd">
> > <responseDate>2015-04-09T10:56:13Z</responseDate>
> > <request verb="ListRecords"  metadataPrefix="oai_dc">http://144.6.225.213:80/geonetwork/srv/en/oaipmh</request>
> > <ListRecords>
> > <record>
> > <header>
> >     <identifier>2714a7f3-338a-4d14-b8e6-23a504108442</identifier>
> >     <datestamp>2015-03-26T14:26:59Z</datestamp>
> >  </header>
> >        .......
> > 
> > The same from GeoNode (which doesn't work) - elements are prefixed by
> > "oai:"
> > 
> > <oai:OAI-PMH xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
> > oai:responseDate2015-04-08T20:15:24Z/oai:responseDate
> > <oai:request metadataprefix="oai_dc" verb="ListRecords">http://144.6.225.213/catalogue/csw?mode=oaipmh/oai:request
> > oai:ListRecords
> > oai:record
> > oai:header
> >     oai:identifier3eecd6aa-d745-11e4-b68d-fa163eac73e2/oai:identifier
> >     oai:dateStamp/
> >     oai:setSpec/
> > /oai:header
> >        .......
> > 
> > Need to see if this is correct XML for harvesting (I haven't found an
> > example of the use of the oai: namespace), and whether this is actually
> > causing the Omeka Plugin to ignore the response
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ozmeka/ozmeka/issues/16#issuecomment-91084180.
> 
> ## 
> 
> Peter Sefton +61410326955 pt@ptsefton.com http://ptsefton.com
> Gmail, Twitter & Skype name: ptsefton

## 

Peter Sefton +61410326955 pt@ptsefton.com http://ptsefton.com
Gmail, Twitter & Skype name: ptsefton

**Comment by ptsefton** [comment]
Forget all that stuff I said about namespaces - I was not looking carefully
enough.

On Thu, Apr 9, 2015 at 11:40 AM, Peter (pt) Sefton pt@ptsefton.com wrote:

> Actually - I got that wrong about the namespace it has the correct one
> from the spec  as a constant.
> 
> https://github.com/omeka/plugin-OaipmhHarvester/blob/master/models/OaipmhHarvester/Harvest/OaiDc.php#L22
> 
> On Thu, Apr 9, 2015 at 11:37 AM, Peter (pt) Sefton pt@ptsefton.com
> wrote:
> 
> > If you look at the namespaces they are different.
> > 
> > The one that works has an implicit namespace of :
> > http://www.openarchives.org/OAI/2.0/
> > 
> > The one that doesn't work has an explicit namespace of
> > http://www.openarchives.org/OAI/2.0/oai_dc/ - which appears to be
> > correct as per the spec:
> > http://www.openarchives.org/OAI/openarchivesprotocol.html
> > 
> > If it is using an XML parser then this could be the problem - not the use
> > of the prefix but the URI for the namespace is unexpected the plugin is
> > hard coded to use the shorter version:
> > https://github.com/omeka/plugin-OaipmhHarvester/blob/master/models/OaipmhHarvester/Harvest/OaiDc.php
> > 
> > On Thu, Apr 9, 2015 at 11:18 AM, Kevin Davies notifications@github.com
> > wrote:
> > 
> > > A "ListRecords" response against a GeoNetwork (which works with Omeka):
> > > 
> > > <OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI- PMH.xsd">
> > > <responseDate>2015-04-09T10:56:13Z</responseDate>
> > > <request verb="ListRecords"  metadataPrefix="oai_dc">http://144.6.225.213:80/geonetwork/srv/en/oaipmh</request>
> > > <ListRecords>
> > > <record>
> > > <header>
> > >     <identifier>2714a7f3-338a-4d14-b8e6-23a504108442</identifier>
> > >     <datestamp>2015-03-26T14:26:59Z</datestamp>
> > >  </header>
> > >        .......
> > > 
> > > The same from GeoNode (which doesn't work) - elements are prefixed by
> > > "oai:"
> > > 
> > > <oai:OAI-PMH xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
> > > oai:responseDate2015-04-08T20:15:24Z/oai:responseDate
> > > <oai:request metadataprefix="oai_dc" verb="ListRecords">http://144.6.225.213/catalogue/csw?mode=oaipmh/oai:request
> > > oai:ListRecords
> > > oai:record
> > > oai:header
> > >     oai:identifier3eecd6aa-d745-11e4-b68d-fa163eac73e2/oai:identifier
> > >     oai:dateStamp/
> > >     oai:setSpec/
> > > /oai:header
> > >        .......
> > > 
> > > Need to see if this is correct XML for harvesting (I haven't found an
> > > example of the use of the oai: namespace), and whether this is actually
> > > causing the Omeka Plugin to ignore the response
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ozmeka/ozmeka/issues/16#issuecomment-91084180.
> > 
> > ## 
> > 
> > Peter Sefton +61410326955 pt@ptsefton.com http://ptsefton.com
> > Gmail, Twitter & Skype name: ptsefton
> 
> ## 
> 
> Peter Sefton +61410326955 pt@ptsefton.com http://ptsefton.com
> Gmail, Twitter & Skype name: ptsefton

## 

Peter Sefton +61410326955 pt@ptsefton.com http://ptsefton.com
Gmail, Twitter & Skype name: ptsefton

**Comment by kevinpdavies** [comment]
The Identify and ListSets verbs from GeoNode validate OK using http://validator.oaipmh.com
Omeka doesn't seem to list the datasets when harvesting GeoNode so the Omeka plugin is the suspect. 

However, the ListRecords verb from GeoNode does not validate OK so is also a problem with the python CSW service. 

Given that the Python CSW can be swapped out for another CSW service in GeoNode (such as GeoNetwork), I will focus on identifying the issue with the Omeka Plugin first.

**Comment by kevinpdavies** [comment]
This is caused by the Omeka Harvester plugin. When it parses the XML, it expects the OAI-PMH response XML to be the default namespace (implicit) as Geonetwork provides. If an explicit namespace is used, as Geonode provides, no attributes are found in the default namespace, and no error is thrown. I tested this by explicitly setting the namespace to "oai" in the XML parser (simplexml_load_string in Request.php) and the ListSets now works with GeoNode. ListRecords still fails, however, with an XML error (as I thought it might).

So there are two tasks to come from this: first. I will need to make a pull request for the Omeka harvester to explicitly check whether the default namespace or an implicit namespace is being used and set the option on the parser appropriately. And second, make a pull request for Geocode/pycsw to use the correct OAI-PMH tags (hopefully this is minor fix).

**Comment by kevinpdavies** [comment]
The second issue with ListRecords is caused by GeoNode/pycsw. When a resumptionToken is supplied, the metadataPrefix is optional, and omeka is not providing it. GeoNode is incorrectly expecting it so fails on the second listRecords request. Will make a fix to pycsw.

Will need to speak with Thom about how to best integrate change to Ozmeka and pull request to Omeka but can wait until next week.

**Comment by kevinpdavies** [comment]
I have made a fix to pycsw so the Omeka/GeoNode harvest now works, but it will only support DC for now. pycsw needs to encode the metadataprefix in the resumpptiontoken so the server can remain stateless between requests. This is a bigger fix which is out of the scope of this project, so I have raised an issue with pycsw.

**Comment by kevinpdavies** [comment]
I have increased the max records from 10 to 1000 on Geonode as suggested by Sharyn. If there are more than 1000 records, subsequent ListRecords will alway be returned as DC - I can deal with this problem when (and if it arises).
