### ISSUE TITLE
Modal dialogue boxes to accept T&Cs

### ISSUE THREAD

**Issue by bushchannelstepper** [ozmeka/ozmeka#19]
On their first visit to the site, users need to be greeted with a modal dialogue where they accept that they may (for instance) see images of deceased people if they continue.

**Comment by bushchannelstepper** [comment]
Now provided by https://github.com/ozmeka/plugin-TCsDialogue.  Feedback welcome

**Comment by sharynys** [comment]
(h1) Important Notices

(h2) Aboriginal and Torres Strait Islander people: 
(p) Please be aware that this website may contain voices, images and/or names of deceased persons. If you wish to discuss the inclusion of material in this archive, please email atsida@lib.uts.edu.au.  

(h2) All users: 
(p) Please note that, as far as possible, research materials on this site are provided ‘as is’. Where views are provided, these may not necessarily reflect the views of UTS and may reflect views from a period which would not be considered appropriate today.

(p) Although many materials on this website are licensed CC-BY, please note that some materials have restricted licenses, and some cannot be licensed for reuse other than by the copyright holders.  Before copying or reusing materials on this site, please ensure that you check the Access rights and License (if any).

(p) By clicking continue, you agree that you will comply with these conditions.

[continue]

**Comment by bushchannelstepper** [comment]
New terms visible on http://womeka.dev.bigblock.com.au/

Can be "reset" by deleting cookie named "dharmae_tncs"
