### ISSUE TITLE
Stage: Adding an item now throws an error on " save", but saves anyway 

### ISSUE THREAD

**Issue by sharynys** [ozmeka/ozmeka#26]

**Comment by bushchannelstepper** [comment]
This was caused by the target page not expecting empty URI fields.  Fix now pushed to stage.

Further to that, SOLR wasn't running which caused the same behaviour until I disabled its plugin (for the moment).  Paul still working on SOLR config for production, I think.

**Comment by bushchannelstepper** [comment]
SOLR plugin and core upgraded on dev.
