### ISSUE TITLE
Stage: (LCSuggest) user can enter & save invalid URI

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#27]
This creates linkable text which produces an Omeka error. Should we allow/enforce only valid URIs in this field? 
SW adds: Carmi you may need to provide more detail? I can only reproduce this if I add a URL manually, instead of selecting from the dropdown. In this case the problem is caused by a relative instead of absolute link

**Comment by ccronje** [comment]
The issue I was referring to is when a text-string is entered in the URI field

**Comment by bushchannelstepper** [comment]
Have implemented PHP's native URL filter to validate URIs.  Change is staged
