### ISSUE TITLE
Stage: (Item Relations) auto complete not working

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#28]
This issue refers to the auto-complete functionality Thom implemented, however it is not working for ID/manual entry.

**Comment by ccronje** [comment]
Last time I noticed this working was 15th April - & not working on 23rd April.

**Comment by bushchannelstepper** [comment]
Fix for this now staged.

**Comment by bushchannelstepper** [comment]
Also staged (on womeka.stage) fix to allow manual entry of IDs as per original plugin.
