### ISSUE TITLE
Investigate whether the behaviour of an item with more than one image can be changed to 1. display file metadata, 2. behave in the same manner regardless of whether tiff/jpeg (see comments)

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#29]
One of our collections contains items with multiple images. In the user interface the images are displayed in a thumbnail grid.

Two issues we'd like to tackle:
1. In some cases, images within an item have different rights holders - we need to state these clearly
2. Currently when a user clicks on an item's image thumbnail:
- jpeg thumbnails are displayed full-screen in the browser
- tiff thumbnails are downloaded by default

We'd like to change these behaviours so that when a user clicks a thumbnail image (regardless of mime type) it is displayed in the browser with the image file metadata (e.g. DC.Title & DC.RightsHolder).

**Comment by bushchannelstepper** [comment]
Can you please link to an item or two that exhibits the problem?  Does it occur in the public section, admin section or both?  Thanks

**Comment by bushchannelstepper** [comment]
This is fixed by altering the theme file items/show.php

The theme's call to the item_image_gallery() function (which is defined in globals.php) just needs to have the third argument set to True, i.e.

item_image_gallery(array(), 'square_thumbnail', true);

Guess we should put the theme into Git as well.

**Comment by bushchannelstepper** [comment]
Is forked at https://github.com/ozmeka/theme-seasons .. have issued a pull request upstream
