### ISSUE TITLE
Stage: Dropbox plugin - ImageMagick error (see comment)

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#31]
Error = "ImageMagick is not properly configured: invalid directory given for the ImageMagick command!"

This error occurs in the Dropbox plugin when the omeka logo (included by default) is selected for upload. 

We will need to test this plugin with other images after issue #30 resolved.

**Comment by DanielTosello** [comment]
quick steps to try when you have the ability to do so: 

check to ensure imagemagick is actually installed and stuff: 
`~]$ which convert`
`~]$ convert --version`

Make sure php isn't limiting execution via the open_basedir restriction (http://php.net/manual/en/ini.core.php#ini.open-basedir)

Obviously both of those require shell access, so i hope that's possible. Hope that helps.

**Comment by bushchannelstepper** [comment]
Thanks for suggestions Daniel.

As it transpires, Omeka needed to see "/usr/local/bin/" rather than "/usr/local/bin/convert".  Seems happy now
