### ISSUE TITLE
Friendly names for item relations not showing up

### ISSUE THREAD

**Issue by ptsefton** [ozmeka/ozmeka#33]
For example, where you have a dc:Creator relation it shows up as Creator rather than Was Created By.

Eg here: http://test-omeka.research.uts.edu.au/items/show/160

**Comment by bushchannelstepper** [comment]
Fairly confident this isn't a bug, but it does need to be configured to use the friendly terms at http://test-omeka.research.uts.edu.au//admin/plugins/config?name=ItemRelations ... think Paul is the only one with access to that page right now though.

**Comment by sharynys** [comment]
Hey Thom, where are the friendly terms stored? We may need to change some...

**Comment by bushchannelstepper** [comment]
They are based in the formal_relations.php file - you should still have a copy of this that you can modify?  If not, let me know.  When the plugin is installed they get loaded into the database as well.

**Comment by bushchannelstepper** [comment]
Correction - they're in plugins/ItemRelations/formal_vocabularies.php

**Comment by bushchannelstepper** [comment]
Presently implementing an upgrade hook in the plugin to add these in cases where an earlier version of the item relations plugin predating the friendly terms is installed.  Right now that's dev, stage and production.

**Comment by ptsefton** [comment]
I think it's not working. Just did a fresh install of Omeka 2.3 with the head of ItemRelations. The formal-vocabularies.php file has this:

```
array(
                'local_part' => 'creator',
                'friendly_part' => 'Was Created By',
                'label' => 'Creator',
                'description' => 'An entity primarily responsible for making the resource.'
            ),
```

I have select FriendlyPart in the ItemRelations plugin config but I still see.

"some item" | Creator | this item 

instead of "Was Created By"

**Comment by bushchannelstepper** [comment]
Please test again now.  Whenever our Item Relations plugin detects that there's no column in the db for friendly_part, it creates and populates it.  Should work with fresh and existing installs.  Please let me know if it doesn't behave as you expect.

**Comment by bushchannelstepper** [comment]
Still not displaying.  Please hold off testing till I can figure out where the regression's from.

**Comment by bushchannelstepper** [comment]
This should be working as intended now and can be tested on dev-omeka.
