### ISSUE TITLE
Improve display of Item Relations in ItemRelations plugin

### ISSUE THREAD

**Issue by ptsefton** [ozmeka/ozmeka#34]
Where there are multiple item relations of the same type, do some UI work to make the page more compact. Most important for the hook for the public view, but useful if the same thing could work in the admin UI as well.
- Only show the relation name once.
- Show the first few with a (+) to expand and see the rest

eg

```
This item  Has Subject  Subject 1
                        Subject 2 
                        (see more)

Book1    Was Created By  This item
Book2
(see more)
```

**Comment by bushchannelstepper** [comment]
This now collates the items by relation type - can be seen on dev-omeka.  Still need to add tree menu.

**Comment by bushchannelstepper** [comment]
Rather than tree menu, have just added "show more" when > 2 items linked to by same relation, with 'show less' option once expanded.  Can be seen at http://dev-omeka.research.uts.edu.au/items/show/395

**Comment by DanielTosello** [comment]
Looks good.

And then i realized i forgot to add the code i did for this to my fork like
i said i was gunna :/

Sorry guys, a bit vague at the moment.

**Comment by bushchannelstepper** [comment]
Example of the reverse side found at http://dev-omeka.research.uts.edu.au/items/show/185
