### ISSUE TITLE
On production server, Omeka produces notification error/message when 'Add Input' selected in DC Coverage & Spatial Coverage fields (see steps below)

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#36]
Steps:
-Edit an Item OR Collection
-In DC Coverage OR Spatial Coverage select Add Input
-Omeka message 'Notice: Undefined index: uri in /var/www/html/omeka-2.3/plugins/LinkedDataElements/models/Mixin/ElementText.php on line 587'

(Note: Data entered is saved.)

**Comment by ccronje** [comment]
Update: Noticed this occurs for every Add Input button except for DC Subject.

**Comment by bushchannelstepper** [comment]
Thanks Carmi,

Patch applied to handle this in https://github.com/ozmeka/LinkedDataElements/tree/v0.4b

Please test on dev-omeka
