### ISSUE TITLE
On production server, deleting an Item produces an error (see below)

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#37]
Omeka has encountered an error

BadMethodCallException
Method named 'findByItemId' does not exist or is not callable.

exception 'BadMethodCallException' with message 'Method named 'findByItemId' does not exist or is not callable.' in /var/www/html/omeka-2.3/application/libraries/Omeka/Db/Table.php:83
Stack trace:
#0 /var/www/html/omeka-2.3/plugins/OaipmhHarvester/OaipmhHarvesterPlugin.php(216): Omeka_Db_Table->__call('findByItemId', Array)
#1 /var/www/html/omeka-2.3/plugins/OaipmhHarvester/OaipmhHarvesterPlugin.php(216): Omeka_Db_Table->findByItemId(386)
#2 [internal function]: OaipmhHarvesterPlugin->hookBeforeDeleteItem(Array)
#3 /var/www/html/omeka-2.3/application/libraries/Omeka/Plugin/Broker.php(157): call_user_func(Array, Array)
#4 /var/www/html/omeka-2.3/application/libraries/Omeka/Record/AbstractRecord.php(298): Omeka_Plugin_Broker->callHook('before_delete_i...', Array)
#5 /var/www/html/omeka-2.3/application/libraries/Omeka/Record/AbstractRecord.php(580): Omeka_Record_AbstractRecord->runCallbacks('beforeDelete')
#6 /var/www/html/omeka-2.3/application/libraries/Omeka/Controller/AbstractActionController.php(283): Omeka_Record_AbstractRecord->delete()
#7 /var/www/html/omeka-2.3/application/libraries/Zend/Controller/Action.php(516): Omeka_Controller_AbstractActionController->deleteAction()
#8 /var/www/html/omeka-2.3/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('deleteAction')
#9 /var/www/html/omeka-2.3/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/html/omeka-2.3/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /var/www/html/omeka-2.3/application/libraries/Zend/Application.php(382): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/html/omeka-2.3/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#13 /var/www/html/omeka-2.3/admin/index.php(28): Omeka_Application->run()
#14 {main}

**Comment by sharynys** [comment]
This happens on test-omeka as well. Its a bug we missed and one that is worrying me. Can we please prioritise this one Thom?

**Comment by bushchannelstepper** [comment]
It wouldn't have shown up in testing until the OaiPmh Harvester plugin was installed.  I can't see any other reference to this method besides the one in there:

./plugins/OaipmhHarvester/OaipmhHarvesterPlugin.php:        $record = $recordTable->findByItemId($id);

**Comment by bushchannelstepper** [comment]
The plugin was old and/or corrupted on dev.  I notice quite a few of the other plugins on dev were out of date when I started configuring it.  Would explain the DB weirdness we saw the other day.  

Have pulled down latest version of OaipmhHarvester plugin on dev, which includes a definition for the previously missing method.  Stage and production may need similar treatment.

**Comment by bushchannelstepper** [comment]
Confirmed problematic plugin installs on stage and production.  We will need to audit the plugins installed in production and ensure they're latest stable versions, and complete.

**Comment by bushchannelstepper** [comment]
Paul's gone through the plugins and sorted this out.  Please advise if further problems.
