### ISSUE TITLE
SCOT/LCsuggest plugin cutting off LCSH list then not bringing term to top of list (see below)

### ISSUE THREAD

**Issue by ccronje** [ozmeka/ozmeka#39]
The list for LCSH isn't allowing scrolling to reveal all options (seems to be fixed with the first 10 options available). So when you enter a concept like _Fish stocking_ or _Fish regulations_ or _Fishery law and legislation_ (which do exist in LCSH) - they are initially cut off from the list as you type _Fish_ - then when you complete typing they aren't being brought to the top of the list.

Tested in Dharmae.

**Comment by bushchannelstepper** [comment]
This looks like an artifact of the LCSH lookup service.  It's basically returning their results verbatim.  I had a look around their site to see if more arguments can be given to the API for more results (and other switches) but couldn't find any reference to such.

**Comment by ccronje** [comment]
Update: We have collected a spreadsheet of LCSH terms that reproduce this issue (we worked around by manually adding URLs).

**Comment by bushchannelstepper** [comment]
Seems to be baked into the web services rather than the plugin.  Not sure why, but I couldn't find any configuration switches in the WS calls to alter this behaviour.
