### ISSUE TITLE
Collection page doesn't paginate items list

### ISSUE THREAD

**Issue by sharynys** [ozmeka/ozmeka#47]
e.g. http://dharmae.research.uts.edu.au/collections/show/24 
On the collection page only the first ten items are listed (good), but there is no paging (bad)

**Comment by bushchannelstepper** [comment]
Discussion here shows altering core files would be required:  http://omeka.org/forums/topic/only-5-items-being-shown-on-collection-page-please-help

Suggestions include altering the text in application/views/scripts/collections/show.php to be more descriptive, i.e. that it's merely displaying a sample and all items can be browsed by clicking through.  This seems the least precarious option.  I'll create a note on upgrading in the ozmeka wiki as this isn't the first change to core.

**Comment by bushchannelstepper** [comment]
Changed link text to "Sample of items in the Talking Fish Collection (click here for all items)"
