### ISSUE TITLE
Investigate whether it would be possible to add URIs as well as text values for metadata elements

### ISSUE THREAD

**Issue by ptsefton** [ozmeka/ozmeka#8]
Could the item relations plugin add a URI field to elements so that we can store a URI as well as a string value, eg for vocab terms that have been looked up, or external relations like DC creator where we have a name string as well as an ORCID or other URI

**Comment by bushchannelstepper** [comment]
Looks like we can copy the core Element class definition file from application/models/Element.php into plugins/ItemRelations/models/ , modify it, then load it with require_once in plugins/ItemRelations/ItemRelationsPlugin.php , then the system will use our modified copy.  Not sure if this is guaranteed to load first in all situations but probably enough to get started.  Looking at db schema next.

**Comment by ptsefton** [comment]
Thinking about this a bit more, if we do decide to do this it would probably make sense to create it as a plugin called something like "Linked data elements" and supply some lookup code along the lines of Fill My List.

**Comment by bushchannelstepper** [comment]
Working on this.  Can confirm copies of the relevant core files (relating to ElementText, I believe) can be safely overridden from the plugin.  Have the form marked up.  Presently threading through the code to store these URI values which is going to take some time longer.

**Comment by bushchannelstepper** [comment]
Working on this.  Can confirm copies of the relevant core files (relating to ElementText, I believe) can be safely overridden from the plugin.  Have the form marked up.  Presently threading through the code to store these URI values which is going to take some time longer.

**Comment by bushchannelstepper** [comment]
Have URIs saving to db now.  There's no validation on the field yet.  Any thoughts on what might be good there?  

Working on retrieving the URI field for display in the form now.

**Comment by bushchannelstepper** [comment]
URIs now get retrieved and populated in the form.  Validation has been added for the case when a URI is present but no text entry, where an error message is shown.

**Comment by bushchannelstepper** [comment]
Patched against Omeka 2.3

**Comment by bushchannelstepper** [comment]
If an Element Text has an associated URI it's now rendered as a link which will open in a new tab.

**Comment by bushchannelstepper** [comment]
Now uses LcSuggest element/lookup bindings to determine whether to present a URI field with each element.

**Comment by bushchannelstepper** [comment]
Linked Data Elements plugin updated to expose URI parameter via Items API
