### ISSUE TITLE
Provide English gloss for item relations and display it instead of the raw term

### ISSUE THREAD

**Issue by ptsefton** [ozmeka/ozmeka#9]
Depends on #9

Add a field for a displayable version of a relation so we can have

```
This Item *is part of* Darling River - Bourke to Brewarrina
This Item *has creator* Heather Goodall
```

Instead of:

```
This Item dcterms:isPartOf Darling River - Bourke to Brewarrina
This Item dcterms:creator Heather Goodall
```

**Comment by bushchannelstepper** [comment]
This is drafted on my dev instance.  Need a list of the human-friendly local_part terms to put into the db now.

**Comment by bushchannelstepper** [comment]
This is uploaded now.  "Friendly part" needs to be selected in plugin config to use.

**Comment by bushchannelstepper** [comment]
Just noting that where "friendly part" field is selected in plugin config and blank in an instance, it falls through to the existing label.

**Comment by ptsefton** [comment]
That seems like a good way to do it
